(function(e){var f=window.AmazonUIPageJS||window.P,h=f._namespace||f.attributeErrors,c=h?h("HzYourOrdersSearchServiceJS",""):f;c.guardFatal?c.guardFatal(e)(c,window):c.execute(function(){e(c,window)})})(function(e,f,h){e.when("jQuery","yo-search.selectors","ready").execute(function(c,d){function b(){var a=c(d.searchInput);return a.length?(a.val()||"").trim():""}function a(){var a=d.closeIcon;c(a).hasClass("aok-hidden")&&c(a).removeClass("aok-hidden");a=d.searchInput;var b=d.searchInputWithCloseIcon;
c(a).hasClass(b)||c(a).addClass(b)}function k(){var a=d.closeIcon;c(a).hasClass("aok-hidden")||c(a).addClass("aok-hidden");a=d.searchInput;var b=d.searchInputWithCloseIcon;c(a).hasClass(b)&&c(a).removeClass(b)}0<b().length&&a();c(d.searchInput).keyup(function(c){0<b().length?a():k()});c(d.closeIcon).click(function(a){a.stopPropagation();a.preventDefault();c(d.searchInput).val("");k()})});"use strict";e.when("A","yo-search.loading-display","ready").register("yo-search.content-loader",function(c,d){var b=
function(a,b,c){c=c||{};this._counterLogger=a;this._ajaxMetricsLogger=b;this._statesByOperation=c.statesByOperation||{};this._loadingDisplay=d};b.DEFAULT_AJAX_TIMEOUT_IN_MILLISECONDS=15E3;b.YOUR_ORDERS_SEARCH_PAGE_ENDPOINT="/your-orders/search";b.OPERATIONS={LOAD_NEXT_PAGE:"load_next_page"};b.currentPage=h;b.hasPageMatched=!1;b.prototype.loadNextSearchResultsPage=function(){if(!this._isOperationActive(b.OPERATIONS.LOAD_NEXT_PAGE)){var a=c.state("page-state")||{};a.nextPage!==h&&(b.currentPage!==a.nextPage?
(b.currentPage=a.nextPage,b.hasPageMatched=!1):b.currentPage===a.nextPage&&(a.nextPage=h,b.hasPageMatched||c.trigger("yo-search:page-state:no-next-page"),b.hasPageMatched=!0));if(a.nextPage){var d={},g={};g.page=a.nextPage;g.search=a.queryString;g.ref_=a.refMarker;d.ajaxParameters=g;d.ajaxMetricsLogger=this._ajaxMetricsLogger;this._loadingDisplay.start();return this._loadContentAsynchronously(b.YOUR_ORDERS_SEARCH_PAGE_ENDPOINT,b.OPERATIONS.LOAD_NEXT_PAGE,d)}}};b.prototype._loadContentAsynchronously=
function(a,d,g){g=g||{};var k=g.ajaxParameters||{},f=g.ajaxTimeout||b.DEFAULT_AJAX_TIMEOUT_IN_MILLISECONDS,e=g.ajaxMetricsLogger,l=this,h=c.$.Deferred(c.$.proxy(this._attachAjaxOperationHandlers,this));e.setPreAjax();g=c.ajax(a,{headers:{Accept:"application/json"},method:"get",timeout:f,params:k,success:function(){h.resolveWith(l,[{ajaxMetricsLogger:e,operation:d}])},abort:function(){h.rejectWith(l,[{ajaxMetricsLogger:e,failureType:"abort",operation:d,url:a}])},error:function(b,c){h.rejectWith(l,
[{ajaxMetricsLogger:e,failureType:"error",operation:d,url:a,xhr:b,statusText:c}])}});this._setOperationState(d,{active:!0,handle:g});return h.promise({ajaxHandle:g})};b.prototype._attachAjaxOperationHandlers=function(a){a.done(this._onSuccess).fail(this._onFail).always(this._onFinish)};b.prototype._onFinish=function(a){this._setOperationState(a.operation,{active:!1})};b.prototype._onSuccess=function(a){a.ajaxMetricsLogger.setPostAjax();a.ajaxMetricsLogger.publishAjaxMetrics();this._loadingDisplay.stop()};
b.prototype._onFail=function(a){a.ajaxMetricsLogger.setPostAjax();if("error"===a.failureType){this._counterLogger.incrementAndPostBack("hzsearchajax:contentloader:"+a.operation+":error");this._abortAllActiveAjaxOperations();this._loadingDisplay.stop();if("Request Timeout"===a.statusText||a.xhr&&a.xhr.http&&400<=a.xhr.http.status&&500!==a.xhr.http.status)f.location.href=a.url,this._counterLogger.incrementAndPostBack("hzsearchajax:contentloader:"+a.operation+":refresh");c.state("chunkState",{nextPage:null})}};
b.prototype._abortAllActiveAjaxOperations=function(){for(var a in this._statesByOperation)this._statesByOperation.hasOwnProperty(a)&&this._abortOperation(a)};b.prototype._abortOperation=function(a){(a=this._statesByOperation[a])&&a.active&&a.handle&&a.handle.abort&&a.handle.abort()};b.prototype._isOperationActive=function(a){return this._statesByOperation[a]&&this._statesByOperation[a].active};b.prototype._setOperationState=function(a,b){this._statesByOperation[a]=b};return b});"use strict";e.when("A",
"yo-search.selectors","ready").register("yo-search.loading-display",function(c,d){function b(a){this.$element=a}c=c.$(d.spinnerContainer);b.prototype={start:function(){this.$element.show()},stop:function(){this.$element.hide()}};return new b(c)});"use strict";e.when("csm-counter-metrics","csm-ajax-metrics","yo-search.scroll-monitor","yo-search.visibility-controller","yo-search.page-state-monitor","yo-search.content-loader","yo-search.page-initializer","ready").register("component-wirer",function(c,
d,b,a,k,g,e){return{wireComponentsAndStartUp:function(){var f=new d("hzsearchajax"),h=new b,l=new a,m=new k;f=new g(c,f);(new e(h,l,m,f)).initialize()}}});e.when("component-wirer").execute("start up",function(c){c.wireComponentsAndStartUp()});history&&"scrollRestoration"in history?history.scrollRestoration="manual":f.onpopstate=function(){f.scroll(0,0)};"use strict";e.when("A","ready").register("yo-search.page-initializer",function(c){var d=function(b,a,c,d){this._scrollMonitor=b;this._visibilityController=
a;this._pageStateMonitor=c;this._contentLoader=d;this._isInitialized=!1};d.prototype.initialize=function(){if(!this._isInitialized){var b=c.$.proxy(this._contentLoader.loadNextSearchResultsPage,this._contentLoader);c.on("yo-search:scroll:bottom",b);c.on("yo-search:page-state:no-next-page",this._visibilityController.showNavFooter);this._pageStateMonitor.enable();this._scrollMonitor.enable();this._isInitialized=!0}};return d});"use strict";e.when("A").register("yo-search.page-state-monitor",function(c){var d=
function(a,b){a.nextPage||c.trigger("yo-search:page-state:no-next-page")},b=function(){this._isEnabled=!1};b.prototype.enable=function(){if(!this._isEnabled){var a=c.state("chunkState")||{};c.state("page-state",a);a.nextPage||c.trigger("yo-search:page-state:no-next-page");c.state.bind("chunkState",function(a,b){c.state("page-state",{nextPage:a.nextPage,refMarker:a.refMarker})});c.state.bind("page-state",d);this._isEnabled=!0}};return b});"use strict";e.when("A","yo-search.selectors","ready").register("yo-search.scroll-monitor",
function(c,d){var b=function(){this._enabled=!1;var a=this;this._checkScrollCallback=function(b){a._checkScroll(b)}};b.prototype.enable=function(){this._enabled||(c.on.scroll(this._checkScrollCallback),this._enabled=!0,this._checkCurrentScroll())};b.prototype.disable=function(){this._enabled&&(c.off("scroll",this._checkScrollCallback),this._enabled=!1)};b.prototype._checkScroll=function(a){var b=a.scrollTop+a.height,f=c.$(d.mobileSearchViewContainer);a=f.offset().top+f.height()-2*a.height;b>a&&c.trigger("yo-search:scroll:bottom")};
b.prototype._checkCurrentScroll=function(){this._checkScroll({scrollTop:c.$(f).scrollTop(),height:c.$(f).height()})};return b});"use strict";e.when("A","yo-search.selectors","ready").register("yo-search.visibility-controller",function(c,d){var b=function(){};b.prototype.showNavFooter=function(){c.$(d.navFooter).show()};return b});"use strict";e.when("A","csm-marker-logger").register("csm-ajax-metrics",function(c,d){return c.createClass({_scope:null,scope:function(b){if(b)this._scope=b;else return this._scope},
init:function(b){this.scope(b)},setPreAjax:function(){d.recordUet("bb",this.scope(),{wb:1})},setPostAjax:function(){d.recordUet("be",this.scope(),{wb:1})},publishAjaxMetrics:function(){d.recordUex("ld",this.scope(),{wb:1})}})});"use strict";e.when("A").register("csm-counter-metrics",function(c){var d=function(a){f.ue&&"function"===typeof f.ue.count&&f.ue.count(a,(f.ue.count(a)||0)+1)},b=function(a){"function"===typeof f.uex&&f.uex("ld",a,{wb:1})};return{increment:d,postBack:b,incrementAndPostBack:function(a){d(a);
b(a)}}});"use strict";e.when("A").register("csm-marker-logger",function(c){return{recordUet:function(c,b,a,e){"function"===typeof f.uet&&f.uet(c,b,a,e)},recordUex:function(c,b,a,e){"function"===typeof f.uex&&f.uex(c,b,a,e)}}});"use strict";e.when("jQuery","yo-search.selectors","ready").execute(function(c,d){function b(a,b){var c=a.text();b=b.replace(/[.*+?^${}()|[\]\\]/g,"\\$\x26");c=c.replace(new RegExp("(\\S)("+b+")(\\S)","gi"),function(a,b,c,d){return b+"\x3cstrong\x3e"+c+"\x3c/strong\x3e"+d});
c=c.replace(/«([^»]+)»/g,function(a,b){return"«\x3cstrong\x3e"+b+"\x3c/strong\x3e»"});a.html(c)}(function(){var a=c(d.searchSummary);if(a.length){var e=String(a.data("searchterm"));e&&b(a,e)}})()});"use strict";e.register("yo-search.selectors",function(){return{closeIcon:"#hzsearch-close-icon",mobileSearchViewContainer:".hzsearch-mobile-content-container",searchInput:"input[name\x3dsearch]",searchInputWithCloseIcon:"hzsearch-text-input",searchSummary:".hzsearch-results-summary",spinnerContainer:".next-page-spinner-container",
navFooter:"footer.nav-mobile"}})});