(function(e){var l=window.AmazonUIPageJS||window.P,m=l._namespace||l.attributeErrors,b=m?m("WebFlowIngressJs",""):l;b.guardFatal?b.guardFatal(e)(b,window):b.execute(function(){e(b,window)})})(function(e,l,m){e.when("jQuery").register("webflow-fetch-experience",function(b){return{fetchExperience:function(b){return fetch(b,{headers:{Accept:"application/vnd.com.amazon.xa+html"}}).then(function(b){if(b.ok)return b.text();throw Error("Network response: "+b.status);}).then(function(b){return{html:b}}).catch(function(b){return{error:b}})},
buildExperienceUrl:function(e,h){var f=new URL(e,l.location);(new URLSearchParams(b.param(h))).forEach(function(b,a){f.searchParams.set(a,b)});return f.toString()}}});e.when("A","a-modal-framework","a-modal-framework-constants").register("webflow-modal",function(b,e,h){return{presentModal:function(f){f={type:"ajax",source:f};var g='\x3cdiv class\x3d"'+h.CONTENT_WRAPPER_CLASS+'"\x3e\x3c/div\x3e';g=b.$('\x3cdiv style\x3d"background-color:white" class\x3d"overlay-container"\x3e\x3c/div\x3e').append("",
'\x3cbutton class\x3d"overlay-close"\x3e\x3cspan class\x3d"a-icon a-icon-close-white"\x3e\x3c/span\x3e\x3c/button\x3e').append(g);f=new e(g,f,{dismissStrategy:"transient",scrimType:"translucent"});f.present();f=f._frameworkWrapper.find(".overlay-close");b.declarative.create(f,"a-modal-framework-dismiss");b.declarative("a-modal-framework-dismiss",["click","keydown"],function(a){var d=b.$(a.$currentTarget).closest("."+constants.FRAMEWORK_WRAPPER_CLASS);if(0!==d.length&&(d=d.data("overlayInstance"))){var c=
"keydown"===a.type&&a.$event.which===b.constants.keycodes.ESCAPE;("click"===a.type||"persistent"!==d._dismissStrategy&&c)&&d.dismiss()}})}}});e.when("A","a-sheet","webflow-fetch-experience","webflow-skeleton-tmp-icdp").register("webflow-bottomsheet",function(b,e,h,f){h=document.createElement("div");h.classList.add("bottomsheet-container");var g=document.createElement("div");g.classList.add("webflow-bottomsheet-instance");g.id="webflow-bottomsheet-instance";Object.assign(g.style,{position:"relative",
height:"100%",width:"100%",overflow:"hidden"});h.append(g);document.body.append(h);var a=e.create({name:"webflow-bottomsheet-instance",preloadDomId:"webflow-bottomsheet-instance",closeType:"icon"});b.on("a:sheet:afterShow:webflow-bottomsheet-instance",function(){a.changeHeight({height:(l.visualViewport?l.visualViewport.height:l.innerHeight)-60})});return{presentBottomSheet:function(b,c){g.innerHTML="";var n=null;if(c&&c.useICDPSkeleton){var k=f.getSkeleton();Object.assign(k.style,{position:"absolute",
top:"0",left:"0",width:"100%",height:"100%",zIndex:"2",transition:"opacity 0.2s ease-in-out",opacity:"1"});g.appendChild(k);n=Date.now()}var d=document.createElement("iframe");b=new URL(b);b.searchParams.append("noNav","1");d.src=b;Object.assign(d.style,{position:"absolute",top:"0",left:"0",width:"100%",height:"100%",border:"none",display:"block"});g.appendChild(d);if(c&&c.useICDPSkeleton){Object.assign(d.style,{visibility:"hidden",zIndex:"1"});var h=setInterval(function(){try{var a=d.contentDocument}catch(p){return}a&&
"complete"===a.readyState&&(clearInterval(h),clearTimeout(l),a=Date.now()-n,setTimeout(function(){d.style.visibility="visible";k&&(k.style.opacity="0",setTimeout(function(){k.parentNode&&k.parentNode.removeChild(k)},200))},Math.max(300-a,0)))},50),l=setTimeout(function(){d.style.visibility="visible";k&&(k.style.opacity="0",setTimeout(function(){k.parentNode&&k.parentNode.removeChild(k)},200));clearInterval(h)},8E3)}e.showSheet(a)}}});e.when("webflow-modal","webflow-bottomsheet","webflow-fetch-experience").register("webflow-routing",
function(b,m,h){function f(a){try{l.top.location.href=a}catch(d){e.logError(d,"Could not change the URL in the parent window:"+a,"ERROR")}}function g(a){a&&"function"===typeof a&&a()}return{show:function(a){try{var d=null;"url"in a.route?d=a.route.url:"web"in a.route&&"url"in a.route.web?d=a.route.web.url:"flow"in a.route&&(d=h.buildExperienceUrl(a.route.flow.endpoint,a.route.flow.inputs));if(null===d)throw Error("Invalid Options Error: no url found");var c=d;"bottom-sheet"==a.presentationConfig.presentationType&&
m.presentBottomSheet(c,a.presentationConfig.bottomSheetConfig);"modal-with-overlay"==a.presentationConfig.presentationType&&b.presentModal(c);"push"==a.presentationConfig.presentationType&&(a.route.url?f(c):a.route.web.url?f(c):(e.logError(null,"fullUrl not available:"+c+", navigating to fallbackUrl","WARN"),f(a.route.flow.fallbackUrl)));g(a.successCallback)}catch(n){throw g(a.failCallback),n;}}}});e.declare("webflow-skeleton-tmp-icdp",{getSkeleton:function(){function b(){var b=a();b.append(c(["webflow-skeleton-tmp-icdp-text-extra-large",
"a-spacing-mini"]),c(["webflow-skeleton-tmp-icdp-text-extra-large","a-spacing-mini"]),c(["webflow-skeleton-tmp-icdp-text-small"]));return b}function e(){var a=c(["a-section"]);a.append(c(["webflow-skeleton-tmp-icdp-image-block","a-spacing-base"]),c(["webflow-skeleton-tmp-icdp-image-swatches","aok-align-center-horizontally"]));return a}function h(){var b=c(),k=a();k.append(c(["webflow-skeleton-tmp-icdp-text-base","a-spacing-mini"]));b.append(d("hr",["a-spacing-mini"]),k,d("hr",["a-spacing-none"]));
return b}function f(){var b=c(),d=a(),e=a(),f=a(),g=a();d.append(c(["webflow-skeleton-tmp-icdp-text-tall-mini","a-spacing-mini"]),c(["webflow-skeleton-tmp-icdp-text-tall-small","a-spacing-mini"]),c(["webflow-skeleton-tmp-icdp-text-small"]));e.append(c(["webflow-skeleton-tmp-icdp-text-micro"]));f.append(c(["webflow-skeleton-tmp-icdp-text-extra-large","a-spacing-mini"]),c(["webflow-skeleton-tmp-icdp-text-extra-large"]));g.append(c(["webflow-skeleton-tmp-icdp-text-medium","a-spacing-mini"]),c(["webflow-skeleton-tmp-icdp-text-large"]));
b.append(d,e,f,g);return b}function g(){var a=c(["a-row","a-padding-base","webflow-skeleton-tmp-icdp-action-bar"]);a.append(c(["a-column","a-spacing-base","webflow-skeleton-tmp-icdp-button"]),c(["a-column","a-spacing-base","webflow-skeleton-tmp-icdp-button","a-span-last"]));return a}function a(){return c(["a-section","a-spacing-none","a-padding-base"])}function d(a,b){a=document.createElement(a);for(var c in b)a.classList.add(b[c]);return a}function c(a){return d("div",a)}return function(){var a=
document.createElement("div");a.append(b(),e(),h(),f(),g());return a}()}})});