'use strict';(function(b){var c=window.AmazonUIPageJS||window.P,d=c._namespace||c.attributeErrors,a=d?d("HorizonteOrderDetailsJS@change-shipping-address","HorizonteOrderDetailsJS"):c;a.guardFatal?a.guardFatal(b)(a,window):a.execute(function(){b(a,window)})})(function(b,c,d){b.when("A","a-sheet","ready").register("change-shipping-address-bottomsheet",function(a,e){function f(a){c.ue&&"function"===typeof c.ue.count&&c.ue.count(a,(c.ue.count(a)||0)+1)}var b=a.state("changeShippingAddressStateData");
if(b&&b.ajaxUrl){var d=b.heading,k=b.ajaxUrl,g=a.$("#changeShippingAddressPreloadContent"),h;a.declarative("changeShippingAddressAction","click",function(b){(b=e.get("changeShippingAddressSheet"))?b.show():(a.show(g),h=e.create({name:"changeShippingAddressSheet",closeType:"icon",preloadDomId:"changeShippingAddressPreloadContent",heading:d}),h.show(),a.ajax(k,{method:"GET",success:function(a){g.html(a);f("HzOD:ChangeShippingAddressBottomSheet:AjaxSuccess")},error:function(a,b,c){f("HzOD:ChangeShippingAddressBottomSheet:AjaxError")}}))})}});
"use strict";b.when("A","a-modal","ready").register("change-shipping-address-modal",function(a,b){b=a.state("changeShippingAddressModalStateData");a.on("a:popover:ajaxSuccess:"+(b&&b.modalName?b.modalName:"change_shipping_address_modal"),function(a){a.popover&&requestAnimationFrame(function(){a.popover.isActive()&&a.popover.updatePosition();requestAnimationFrame(function(){a.popover.isActive()&&a.popover.updatePosition()})})})})});
/* ******** */
'use strict';(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("HorizonteOrderDetailsJS@core","HorizonteOrderDetailsJS"):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){c.register("hzod-core-metrics",function(){function a(a){b.ue&&"function"===typeof b.ue.count&&b.ue.count(a,(b.ue.count(a)||0)+1)}return{countMetric:a,logError:function(c,d){b.ueLogError&&b.ueLogError(d||{message:c},{logLevel:"ERROR",attribution:c});
a(c)}}});c.register("hzod-core-navigation",function(){return{reload:function(){location.reload()}}})});
/* ******** */
'use strict';(function(c){var d=window.AmazonUIPageJS||window.P,b=d._namespace||d.attributeErrors,a=b?b("HorizonteOrderDetailsJS@customer-delivery-profile","HorizonteOrderDetailsJS"):d;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,d,b){c.when("A","a-secondary-view","hzod-core-metrics","ready").register("od-customer-delivery-profile-secondary-view",function(a,c,d){a.declarative("customer-delivery-profile-modal-link","click",function(e){e.$event.preventDefault();
d.countMetric("HzOD:CustomerDeliveryProfile:ButtonClicked",1);var b=a.extend({},e.data);e=e.$currentTarget;b.url=e.find("a").attr("href");b.dataStrategy="ajax";c.create(e,b).show()})})});
/* ******** */
'use strict';(function(b){var c=window.AmazonUIPageJS||window.P,d=c._namespace||c.attributeErrors,a=d?d("HorizonteOrderDetailsJS@delay-approval","HorizonteOrderDetailsJS"):c;a.guardFatal?a.guardFatal(b)(a,window):a.execute(function(){b(a,window)})})(function(b,c,d){b.when("A","hzod-core-metrics","ready").register("hzod-delay-approval",function(a,b){function d(f){var e=a.extend({},f.data);f=e.endpoint+e.endpointQuery;var d={orderId:e.orderId,itemId:e.itemId,csrfToken:h('meta[name\x3d"pt-csrf-token"]').attr("content")};
a.post(f,{params:d,traditional:!0,success:function(a){a.success&&a.value?(b.countMetric("hzod-delay-approval-ajax-success"),c.location.href="/progress-tracker/package"+g(e,"19")):(b.countMetric("hzod-delay-approval-ajax-error"),"INVALID_TOKEN"===a.responseCode&&b.countMetric("hzod-delay-approval-invalid-token"),c.location.href="/progress-tracker/package"+g(e,"3"))},error:function(){b.countMetric("hzod-delay-approval-ajax-error");c.location.href="/progress-tracker/package"+g(e,"3")}})}function g(a,
b){return"?"+h.param({orderId:a.orderId,itemId:a.itemId,noPtRedirect:"1",amzlMessageId:b})}var h=a.$;a.declarative("pt-delay-approval-click",["click"],function(a){a.$event.preventDefault();d(a)})})});
/* ******** */
'use strict';(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("HorizonteOrderDetailsJS@do-not-enter","HorizonteOrderDetailsJS"):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
'use strict';(function(c){var a=window.AmazonUIPageJS||window.P,g=a._namespace||a.attributeErrors,b=g?g("HorizonteOrderDetailsJS@gift-card-share-link","HorizonteOrderDetailsJS"):a;b.guardFatal?b.guardFatal(c)(b,window):b.execute(function(){c(b,window)})})(function(c,a,g){c.when("A","hzod-core-metrics","ready").register("hzod-gift-card-share-link-script",function(b,d){b.declarative("copy-gift-card-share-link","click",function(a){try{var b=a.data.index,c=a.$target.closest(".a-row"),f=c&&c.find(".gift-card-share-link-input"),
e=c&&c.find(".copy-gift-card-link-success");f&&(f.select(),navigator&&navigator.clipboard&&navigator.clipboard.writeText(f[b].value).then(function(){e&&e.stop(!0,!0).fadeIn(200).delay(1500).fadeOut(200);d.countMetric("HzOD:CopyGiftCardShareLink:CopyLinkClicked")}).catch(function(){d.countMetric("HzOD:CopyGiftCardShareLink:CopyLinkError")}))}catch(k){d.countMetric("HzOD:CopyGiftCardShareLink:Error")}});if(a.amazon&&a.amazon.mash)var c=a.amazon.mash;b.declarative("share-gift-card-link","click",function(b){d.countMetric("HzOD:ShareGiftCardLink:EventTriggered",
1);try{var g=b.data.index,h=b.$target.closest(".a-row"),f=h&&h.find(".gift-card-share-link-input");if(f){var e=f[g].value;d.countMetric("HzOD:ShareGiftCardLink:ShareLinkClicked",1);c?(c.share({messagePlain160:e,messagePlain140:e,messageHTML:e,messagePlain:e,subject:e}),d.countMetric("HzOD:ShareGiftCardLink:MashShare:Success",1)):(d.countMetric("HzOD:ShareGiftCardLink:MashUndefined:Error",1),a.navigator&&a.navigator.share?(a.navigator.share({text:e}),d.countMetric("HzOD:ShareGiftCardLink:WindowShare:Success",
1)):d.countMetric("HzOD:ShareGiftCardLink:WindowUndefined:Error",1))}else d.countMetric("HzOD:ShareGiftCardLink:InputUndefined:Error",1)}catch(k){d.countMetric("HzOD:ShareGiftCardLink:Error")}})})});
/* ******** */
'use strict';(function(b){var c=window.AmazonUIPageJS||window.P,d=c._namespace||c.attributeErrors,a=d?d("HorizonteOrderDetailsJS@holiday-cheer","HorizonteOrderDetailsJS"):c;a.guardFatal?a.guardFatal(b)(a,window):a.execute(function(){b(a,window)})})(function(b,c,d){b.declare("holiday-cheer",{isEnabled:!1})});
/* ******** */
'use strict';(function(c){var d=window.AmazonUIPageJS||window.P,h=d._namespace||d.attributeErrors,a=h?h("HorizonteOrderDetailsJS@in-gift-card-share-link","HorizonteOrderDetailsJS"):d;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,d,h){c.when("A","hzod-core-metrics","ready").register("hzod-in-gift-card-share-link-script",function(a,b){a.declarative("in-web-gift-card-share-link","click",function(a){b.countMetric("HzOD:GiftCardShareLink:Web:Clicked",1);try{var c=
a.data.index,k=a.$target.closest(".a-row"),f=k&&k.find(".gift-card-share-link-input");if(f){var g=f[c].value;d.navigator&&d.navigator.share?d.navigator.share({text:g}).then(function(){b.countMetric("HzOD:GiftCardShareLink:Web:ShareSuccess",1)}).catch(function(a){b.countMetric("HzOD:GiftCardShareLink:Web:ShareError",1)}):b.countMetric("HzOD:GiftCardShareLink:Web:Unsupported",1)}else b.countMetric("HzOD:GiftCardShareLink:Web:InputUndefined",1)}catch(e){b.countMetric("HzOD:GiftCardShareLink:Web:Error",
1)}});a.declarative("in-app-gift-card-share-link","click",function(a){b.countMetric("HzOD:GiftCardShareLink:App:Clicked",1);c.when("mash").execute(function(c){try{var d=a.data.index,f=a.$target.closest(".a-row"),g=f&&f.find(".gift-card-share-link-input");if(g){var e=g[d].value;c.share({messagePlain160:e,messagePlain140:e,messageHTML:e,messagePlain:e,subject:e,successCallback:function(){b.countMetric("HzOD:GiftCardShareLink:App:ShareSuccess",1)},failCallback:function(a){b.countMetric("HzOD:GiftCardShareLink:App:ShareError",
1)}})}else b.countMetric("HzOD:GiftCardShareLink:App:InputUndefined",1)}catch(l){b.countMetric("HzOD:GiftCardShareLink:App:Error",1)}})})})});
/* ******** */
'use strict';(function(h){var d=window.AmazonUIPageJS||window.P,g=d._namespace||d.attributeErrors,b=g?g("HorizonteOrderDetailsJS@invoice","HorizonteOrderDetailsJS"):d;b.guardFatal?b.guardFatal(h)(b,window):b.execute(function(){h(b,window)})})(function(h,d,g){h.when("A","a-sheet","a-form-radio-button","a-modal","ready").register("hzod-download-invoice-script",function(b,h,r,w){function x(a){a=a.clone().appendTo("body");b.show(a);var e=a.outerHeight();b.hide(a);a.remove();return e+2}function y(a,e){if(a!==
g&&a){var n=a;h.hideSheet(p);try{if("hzod_printable_order_summary"===e||"hzod_request_invoice"===e)d.location.href=n;else{a=document.createElement("a");a.href=n;if("hzod_pslip"!==e){var c=new URL(n,d.location.origin);c.searchParams.set("attachment","true");a.href=c.pathname+c.search}a.download="";a.click();b.$("#hzod-download-changeover").stop(!0,!0).fadeIn(200).delay(2E3).fadeOut(200)}}catch(J){l("HzOD:DownloadInvoice:DownloadFailed"),q(z,A)}}else l("HzOD:DownloadInvoice:DownloadUnavailable"),q(B,
C)}function q(a,e){var c=b.$("#hzod-popover-trigger");a={header:a,inlineContent:e};b.hide(m);w.create(c,a).show()}function l(a){d.ue&&"function"===typeof d.ue.count&&d.ue.count(a,(d.ue.count(a)||0)+1)}var f=b.state("downloadInvoiceStateData");if(f&&f.orderId){var D=f.orderId,t=f.marketplaceId,E=f.invoiceNotAvailableHeader,F=f.invoiceNotAvailableMessage,z=f.downloadFailedHeader,A=f.downloadFailedMessage,B=f.downloadUnavailableHeader,C=f.downloadUnavailableMessage,m=b.$("#hzod-download-invoice-loading-spinner"),
u=b.$("#hzod-bottom-sheet-content"),G=r('[name\x3d"hzod-invoice"]'),c={},p,k=[{key:"PrintableOrderSummary",optionId:"#hzod-printable-order-summary-option",radioValue:"hzod_printable_order_summary"},{key:"Invoice",optionId:"#hzod-invoice-option",radioValue:"hzod_invoice"},{key:"PSlip",optionId:"#hzod-pslip-option",radioValue:"hzod_pslip"},{key:"CreditNote",optionId:"#hzod-credit-note-option",radioValue:"hzod_credit_note"},{key:"RequestInvoice",optionId:"#hzod-request-invoice-option",radioValue:"hzod_request_invoice"}];
b.declarative("hzod-download-invoice","click",function(a){b.show(m);b.ajax("/your-orders/invoice/popover",{params:{orderId:D},method:"get",contentType:"application/json;charset\x3dUTF-8",timeout:5E3,success:H,error:v})});"function"===typeof d.uet&&d.uet("fn");var H=function(a){let e=JSON.parse(a.replaceAll("\x26quot;",'"'));c={};k.forEach((a)=>{var b=["Invoice","PSlip","CreditNote"].includes(a.key),d=Object.keys(e).find((c)=>c.startsWith(a.key)&&(!b||e[c].url.endsWith(".pdf")));d&&(c[a.key]=e[d])});
"A33AVAJ2PDY3EV"!==t&&"A3CQBQD3RGPJR8"!==t||c.Invoice!==g||c.PSlip===g||(c.Invoice=c.PSlip,c.PSlip=[]);k.some((a)=>c[a.key]!==g)?I():v()},I=function(){var a=h.get("hzod-download-invoice-bottom-sheet");a?(b.hide(m),a.show()):(k.forEach(function(a){var e=b.$(a.optionId);c[a.key]===g?b.hide(e):("PrintableOrderSummary"===a.key||"RequestInvoice"===a.key)&&e.find(".a-radio-label").text(c[a.key].label)}),a={name:"hzod-download-invoice-bottom-sheet",closeType:"icon",preloadDomId:"hzod-bottom-sheet-content",
height:x(u)},b.hide(m),u.addClass("hzod-di-bottom-sheet-content-absolute"),p=h.create(a),p.show(),(a=k.find((a)=>c[a.key]&&c[a.key]!==g))&&r("[id^\x3d'"+a.optionId.substring(1)+"']").prop("checked",!0))},v=function(a){l("HzOD:DownloadInvoice:InvoiceUnavailable");q(E,F)};b.declarative("hzod-download-documents-action","click",function(a){l("HzOD:DownloadInvoice:DownloadDocuments");var b=G.val();(a=k.find((a)=>a.radioValue===b))&&c[a.key]&&y(c[a.key].url,b)})}})});
/* ******** */
'use strict';(function(e){var g=window.AmazonUIPageJS||window.P,h=g._namespace||g.attributeErrors,a=h?h("HorizonteOrderDetailsJS@milestone-bar","HorizonteOrderDetailsJS"):g;a.guardFatal?a.guardFatal(e)(a,window):a.execute(function(){e(a,window)})})(function(e,g,h){e.when("A","ready").register("milestone-bar-animation",function(a){function e(f,b,c,e){f&&a.delay(function(){const b=f.querySelector(".od-milestone-bar-progress");if(b){var d=parseFloat(c);if(!isNaN(d)&&0!==d){var g=Math.round(100*d);d=
e||1>d?500+500*d:500;a.animate(a.$(b),{width:g+"%"},d,"ease-out",function(){b.setAttribute("data-animation-complete","true")})}}},b)}function g(f,b,c,e){f&&c&&a.delay(function(){const b=f.querySelector(".od-milestone-marker"),d=f.querySelector(".od-milestone-marker-check"),c=f.querySelector(".od-milestone-label");b&&d&&c&&(b.style.transitionDuration="250ms",b.classList.add("active"),a.delay(function(){a.animate(a.$(d),{opacity:"1"},250,"ease-out",function(){d.classList.add("active");e&&c.classList.add("active")})},
125))},b)}(function(){document.querySelectorAll(".od-milestone-bar-container").forEach(function(a){a=Array.from(a.querySelectorAll(".od-milestone-segment"));for(var b=0;b<a.length;b++){const c=a[b],f=c.classList.contains("od-first-milestone");f||e(c,500*(b-1)+1E3,c.getAttribute("data-percent-complete"),b===a.length-1);g(c,f?1E3:500*b+1E3,"true"===c.getAttribute("data-reached"),"true"===c.getAttribute("data-last-reached"))}})})()})});
/* ******** */
'use strict';(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("HorizonteOrderDetailsJS@off-amazon-email-copy","HorizonteOrderDetailsJS"):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
'use strict';(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("HorizonteOrderDetailsJS@off-amazon-product-details-page-ingress","HorizonteOrderDetailsJS"):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
'use strict';(function(e){var c=window.AmazonUIPageJS||window.P,f=c._namespace||c.attributeErrors,a=f?f("HorizonteOrderDetailsJS@od-ajax-gc-register","HorizonteOrderDetailsJS"):c;a.guardFatal?a.guardFatal(e)(a,window):a.execute(function(){e(a,window)})})(function(e,c,f){e.when("A","a-truncate","ready").register("od-ajax-gc-register",function(a,e){function f(a){c.ue&&"function"===typeof c.ue.count&&c.ue.count(a,(c.ue.count(a)||0)+1)}a.declarative("od-ajax-gc-request-action","click",function(b){b=b.data;
a.trigger("od-ajax-gc-request-event",b.orderId,b.lineItemId)});a.on("od-ajax-gc-request-event",function(b,c){f("HzOD:ODAjaxGcRegister:AjaxRequest");var d="od-ajax-gc-state-"+c;a.state(d,{showPaginationButton:"false",showSpinner:"true"});var e=1;a.state(d)&&a.state(d).page&&(e=a.state(d).page);a.ajax("/your-orders/order-details/ajax/egc?orderID\x3d"+b+"\x26page\x3d"+e+"\x26lineItemId\x3d"+c,{method:"GET",error:function(){a.state(d,{showPaginationButton:"true",showSpinner:"false"});f("HzOD:ODAjaxGcRegister:AjaxResponseError")}})});
a.on("od-ajax-gc:state-bindings",function(b){a.state.bind("od-ajax-gc-state-"+b,function(c){f("HzOD:ODAjaxGcRegister:StateBindingTriggered");for(var d=0;d<c.unhideMax;d++)a.$("#od-ajax-gc-RECIPIENT-parent-"+b+"-"+d).removeClass("aok-hidden"),a.$("#od-ajax-gc-RECIPIENT-parent-"+b+"-"+d).addClass("a-grid-vertical-align a-grid-center"),a.$("#od-ajax-gc-RECIPIENT-target-"+b+"-"+d).removeAttr("data-a-updated");0<c.unhideMax&&(a.$("#od-ajax-gc-sender-parent-"+b).removeClass("aok-hidden"),a.$("#od-ajax-gc-sender-target-"+
b).removeAttr("data-a-updated"),a.$("#od-ajax-message-parent-"+b).removeClass("aok-hidden"),a.$("#od-ajax-gc-RECIPIENT-parent-"+b+"-header").removeClass("aok-hidden"),a.$("#od-ajax-gc-RECIPIENT-parent-"+b+"-header").addClass("a-grid-vertical-align a-grid-center"),a.$("#od-ajax-gc-RECIPIENT-parent-"+b+"-header").removeAttr("data-a-updated"));"true"===c.showPaginationButton?a.$("#od-ajax-gc-button-"+b).removeClass("aok-hidden"):a.$("#od-ajax-gc-button-"+b).addClass("aok-hidden");"true"===c.showSpinner?
a.$("#od-ajax-gc-spinner-"+b).removeClass("aok-hidden"):a.$("#od-ajax-gc-spinner-"+b).addClass("aok-hidden");e.refreshAutoTruncate()})})})});
/* ******** */
'use strict';(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("HorizonteOrderDetailsJS@share-tracking","HorizonteOrderDetailsJS"):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
'use strict';(function(b){var c=window.AmazonUIPageJS||window.P,d=c._namespace||c.attributeErrors,a=d?d("HorizonteOrderDetailsJS@shipment-expander","HorizonteOrderDetailsJS"):c;a.guardFatal?a.guardFatal(b)(a,window):a.execute(function(){b(a,window)})})(function(b,c,d){b.when("A","a-truncate","ready").register("shipment-expander-refresh-truncate",function(a,b){a.on("a:expander:shipment_expander:toggle:expand",function(){a.$('[data-component\x3d"itemTitle"] .a-truncate').removeAttr("data-a-updated");
b.refreshAutoTruncate()})})});
/* ******** */
'use strict';(function(b){var f=window.AmazonUIPageJS||window.P,h=f._namespace||f.attributeErrors,a=h?h("HorizonteOrderDetailsJS@tips","HorizonteOrderDetailsJS"):f;a.guardFatal?a.guardFatal(b)(a,window):a.execute(function(){b(a,window)})})(function(b,f,h){b.when("A","a-button","a-alert","hzod-core-navigation","hzod-core-metrics","ready").register("hzod-tips-component",function(a,b,f,h,m){const c=a.$("#tips-custom-option-text-input"),n=c.parent(".a-input-text-wrapper"),e=b("#hzod-tips-save-button"),
g=f("#tips-custom-option-text-input-error"),k=a.state("tipsDataState"),l=a.state("customTipOptionState");g.hide();l&&k&&k.isSuggestedOptionsAvailable&&!l.isSelected&&(c.hide(),n.hide());e.length&&e.disable();b=a.debounce(function(d){d=c.val();if(RegExp(/^\d+(\.\d+)?$/).test(d))if(Number(d)>l.maxAmount){g.show().text(k.maxTipAmountAlert);e.disable();var b=!1}else b=!0;else g.show().text(k.invalidInputAlert),e.disable(),b=!1;b&&(g.hide(),e.enable(),d={setTipUrl:l.setTipUrlForCustomOption.concat("\x26",
"amount.amount\x3d",d)},a.state("tipsDataState",d))},300,!1);c.length&&c.bind("input",b);a.declarative("custom-tip-option-click-action","click",function(a){c.show();n.show();c.val("");e.disable()});a.declarative("suggested-tip-option-click-action","click",function(d){(d=d.$target.context.dataset)&&a.state("tipsDataState",{setTipUrl:d.setTipUrl});c.hide();n.hide();g.hide();c.val("");e.enable()});a.declarative("update-tip-button-click","click",function(d){if(e.isEnabled()){e.disable();var b=a.state("tipsDataState");
d={Accept:'application/vnd.com.amazon.api+json; type\x3d"primenow.order/v1"',"Accept-Language":"en-US","Content-Type":'application/vnd.com.amazon.api+json; type\x3d"primenow.order.tip.set-request/v1"',"x-api-csrf-token":a.$("meta[name\x3d'aapi-csrf-token']").attr("content"),"x-amzn-encrypted-slate-token":a.$("meta[name\x3d'encrypted-slate-token']").attr("content")};var c=new URL(b.aapiAjaxEndpoint+b.setTipUrl),f={amount:{currencyCode:c.searchParams.get("amount.currencyCode"),amount:Number(c.searchParams.get("amount.amount"))}};
a.$.ajax({url:`${c.origin}${c.pathname}`,type:"PUT",headers:d,data:JSON.stringify(f),xhrFields:{withCredentials:!0},success:function(a){(a=a&&a.entity&&a.entity.states)&&1===a.length&&"OK"===a[0].type?(m.countMetric("HzOD:Tips:UpdateSuccessful"),h.reload()):(g.show().text(b.updateFailedAlert),e.enable(),m.countMetric("HzOD:Tips:UpdateFailed:TipModFailure"))},error:function(){g.show().text(b.updateFailedAlert);e.enable();m.countMetric("HzOD:Tips:UpdateFailed:Error")}})}})})});
/* ******** */
'use strict';(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("HorizonteOrderDetailsJS@modals","HorizonteOrderDetailsJS"):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
'use strict';(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("HorizonteOrderDetailsJS@verify-transparency","HorizonteOrderDetailsJS"):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
